title: testMore-Dos-Batch                 <script async type="text/javascript">var REPO="testMore-Dos-Batch";</script><script async type="text/javascript" src="/topmenu.js"></script>
description: DOS Batch implementation of Perl's Test::More test framework
